name: EAS Build APK (Production APK)

on:
  push:
    branches:
      - main

jobs:
  eas-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 20.19.4
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install dependencies (Yarn)
        run: yarn install --frozen-lockfile

      - name: Install EAS CLI globally
        run: npm install --global eas-cli

      - name: Build Production APK with EAS
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform android --profile production-apk --non-interactive

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: playcalc-apk
          path: dist/*.apk
