name: EAS Build APK (Production APK)

on:
  push:
    branches:
      - main

jobs:
  eas-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install dependencies (Yarn)
        run: yarn install --frozen-lockfile

      - name: Install EAS CLI
        run: yarn global add eas-cli

      - name: Build APK with EAS (Production APK)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform android --profile production-apk --non-interactive
